model:
  model_name: PMNQP
  prompt_template: ["a photo of x x", "a photo of x", "a photo of x"]
  ctx_init: ["a photo of ", "a photo of ", "a photo of "]
  clip_model: "ViT-L/14"
  adapter_dim: 64
  adapter_dropout: 0.1
  pair_loss_weight: 1.0
  pair_inference_weight: 1.0
  attr_loss_weight: 0.5
  attr_inference_weight: 0.5
  obj_loss_weight: 0.5
  obj_inference_weight: 0.5
  # primitive memory networks
  attr_readout_loss_weight: 0.5
  attr_readout_inference_weight: 0.5
  obj_readout_loss_weight: 0.5
  obj_readout_inference_weight: 0.5
  memory_length: 50
  beta: 5.5
  memorize_text: False
  # qualified three branch
  attr_qualified_loss_weight: 0.01
  attr_qualified_inference_weight: 0.01
  obj_qualified_loss_weight: 0.01
  obj_qualified_inference_weight: 0.01
  qualified_soft_prompt_train: True

train:
  cuda_device: 0
  dataset: mit-states
  # dataset_path:
  optimizer: Adam #AdamW #SGD #Adam
  scheduler: StepLR
  step_size: 5
  gamma: 0.5
  lr: 0.0001
  attr_dropout: 0.3
  weight_decay: 0.00001
  context_length: 8
  train_batch_size: 16
  gradient_accumulation_steps: 1
  seed: 66
  epochs: 10
  epoch_start: 0
  # save_path:
  val_metric: AUC # best_loss
  save_final_model: True
  # load_model: False     # False or model path
  save_every_n: 5

test:
  eval_batch_size: 256
  open_world: False #True # False
  # load_model:
  topk: 1
  text_encoder_batch_size: 1024
  # threshold: 0.4
  threshold_trials: 50
  bias: 0.001
  text_first: True

